### PR TITLE
feat: allow computedInputs to be async

### PR DESCRIPTION
**Pull request by macrozone**
i am testing it out right now, seems to work!

maybe there should be an end-to-end test for that, but i could not run them locally, so i skipped that for the moment

solves https://github.com/graphql-nexus/nexus-plugin-prisma/issues/665

solves https://github.com/graphql-nexus/nexus/issues/1353

### CODE REVIEW

**Comment by macrozone** [comment]
@jasonkuhrt @Weakky would be awesome to get a review soon! I think this feature is really handy for prisma users

**Comment by bennettrogers** [comment]
I would love to see this merged as well - it would make it possible to query the database before returning the computedInputs.

**Comment by macrozone** [comment]
@jasonkuhrt any chance to include that in the next release?

**Comment by macrozone** [comment]
@Weakky @jasonkuhrt  would be cool to get this merged, before we get too much conflicts.

**Review by jasonkuhrt — APPROVED** [review]
LGTM

Please fix conflicts and then we'll merge :)

**Comment by macrozone** [comment]
> LGTM
> 
> Please fix conflicts and then we'll merge :)

done!

**Pull request merged**
