### PR TITLE
feat: support prisma 2 preview 22

### LINKED ISSUE #605: Schema generation error with the latest prisma2 release
OS: `MacOS`
Prisma Version: `2.0.0-preview022`
Nexus Version: `0.12.0-rc.11`
Nexus Prisma Version: `0.9.1`

When I generate schema with nexus-prisma I keep getting this error.

```console
/Users/impowski/Projects/loaders/node_modules/nexus-prisma/src/publisher.ts:126
          .map(field => ({
           ^
TypeError: Cannot read property 'map' of undefined
    at Object.definition (/Users/impowski/Projects/loaders/node_modules/nexus-prisma/src/publisher.ts:126:12)
    at SchemaBuilder.walkInputType (/Users/impowski/Projects/loaders/node_modules/nexus/src/builder.ts:1365:9)
    at SchemaBuilder.walkTypes (/Users/impowski/Projects/loaders/node_modules/nexus/src/builder.ts:679:16)
    at SchemaBuilder.getFinalTypeMap (/Users/impowski/Projects/loaders/node_modules/nexus/src/builder.ts:787:10)
    at makeSchemaInternal (/Users/impowski/Projects/loaders/node_modules/nexus/src/builder.ts:1585:15)
    at Object.makeSchema (/Users/impowski/Projects/loaders/node_modules/nexus/src/builder.ts:1630:49)
    at Object.<anonymous> (/Users/impowski/Projects/loaders/packages/server/src/schema.ts:6:23)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module.m._compile (/Users/impowski/Projects/loaders/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

### LINKED ISSUE #609: Add support for Prisma 2 preview 22

### PR DESCRIPTION
**Pull request by jasonkuhrt**
closes #609 
closes #605

### CODE REVIEW

**Comment by Devlin556** [comment]
Hi! @Weakky 
This pull request doesn't resolve the issue - prisma/prisma2#1640 now. I tested the latest commit in the branch - `feat/prisma-preview-22-support` and here still has an error: `TypeError: Cannot read property 'map' of undefined`. I think this because of the new DMMF format for `after` argument.
`src/publisher.ts:125` Here you should check that `inputType` has fields or find this type by name in the DMMF input types and get his fields from there. 
I really need this update 👍 
Thanks!

**Comment by impowski** [comment]
closes #605

**Comment by jasonkuhrt** [comment]
This PR will probably take until next week. Some complexity with the current codebase handling pagination args going from scalars to input objects.  ~Also oddly something on the codebase is causing my TS Language service with VSCode to crash, which isn't helping.~ ✅ We'll get there.

**Comment by guog** [comment]
@jasonkuhrt Thanks for contributing, on the other side of the planet

**Pull request merged**
