### PR TITLE
fix: fix root type in CustomFieldResolver

### LINKED ISSUE #1004: Wrong typing for custom resolver root
0.27.0 broke the typing.
See https://github.com/graphql-nexus/nexus-plugin-prisma/commit/005972caa9107b96a6e2dcd276f209830c66f574#r45144765

### LINKED ISSUE #1011: Regression in resolve + originalResolve
The `root` type of `resolve` no longer matches the type `originalResolve` wants as its `root` parameter.

```
export const CarrierPhoto = objectType({
	name: 'CarrierPhoto',
	definition(t) {
		t.model.carrierID();
		t.model.src({
			async resolve(root, args, ctx, info, originalResolve) {
				// `root` is of type number | null, however `originalResolve` wants `CarrierPhoto` as first parameter.
				let src = await originalResolve(root as any, args, ctx, info);
				src = src.replace(/\\/g, '/');
				if (!src.startsWith('/')) {
					src = '/' + src;
				}
				return src;
			},
		});
		t.model.order();
	},
});
```

package-lock.json (extract)
```
"nexus": {
  "version": "1.0.0",
},
"nexus-plugin-prisma": {
  "version": "0.27.0",
},
```

### PR DESCRIPTION
**Pull request by P4sca1**
Closes #1004 
Closes #1011

### CODE REVIEW

**Comment by mingchuno** [comment]
`Namespace '"/Users/runner/work/nexus-plugin-prisma/nexus-plugin-prisma/node_modules/nexus/dist/core"' has no exported member 'RootValue'.` ?

**Comment by P4sca1** [comment]
@mingchuno I just reverted the change which did not work, because in newer versions of nexus, `RootValue` has been renamed to `SourceValue`. I pushed another commit which should resolve this issue.

**Review by mingchuno — APPROVED** [review]
This LGTM

**Comment by jasonkuhrt** [comment]
ty!

**Comment by Akxe** [comment]
@P4sca1 @jasonkuhrt Is it really fixed? I just updated to nexus v28 and prisma v14, yet the types are still not right

This code:
```ts
export const CarrierPhoto = objectType({
  name: 'CarrierPhoto',
  definition(t) {
    t.model.carrierID();
    t.model.src({
      // arguments: [root: string, args: {}, ctx: Context, info: GraphQLResolveInfo, originalResolve: FieldResolver<"CarrierPhoto", "src">]
      async resolve(root, args, ctx, info, originalResolve) {
        // (parameter) originalResolve: (source: CarrierPhoto, args: {}, context: Context, info: GraphQLResolveInfo) => MaybePromise<string>] 
        let src = await originalResolve(root as any, args, ctx, info);
        src = src.replace(/\\/g, '/');
        if (!src.startsWith('/')) {
          src = '/' + src;
        }
        return src;
      },
    });
    t.model.order();
  },
});
```

**Comment by jasonkuhrt** [comment]
This patch is released on a canary. Can you please try it and report back?

**Comment by Akxe** [comment]
How to install the canary?

**Comment by jasonkuhrt** [comment]
`npm add nexus-plugin-prisma@next`

**Pull request merged**
