### PR TITLE
feat(deps): update prisma to v2.15.0

### LINKED ISSUE #1029: Support for prisma 2.15.0
Hey, 
I wanted to test out some new prisma features, but since I'm getting this warning I was a little reluctant. 

"Warning: nexus-plugin-prisma@0.28.0 does not support @prisma/client@2.15.0. The supported range is: `2.14.x`. This could lead to undefined behaviors and bugs."

Could someone clarify to me what are the plans for a future release that supports prisma 2.15.0?
Thanks.

### PR DESCRIPTION
**Pull request by lvauvillier**
Fixes to make it working with prisma 2.15

closes #1029
fix #1028

### CODE REVIEW

**Review by jasonkuhrt — APPROVED** [review]
Thanks @lvauvillier !

**Review by jasonkuhrt — CHANGES_REQUESTED** [review]
Ah, one thing. Can you please update the package.json (and lock) to use Prisma 2.15.

**Comment by lvauvillier** [comment]
@jasonkuhrt, this PR is based on the renovate/prisma branch. So, package.json and yarn.lock has already been updated.

**Comment by jasonkuhrt** [comment]
@lvauvillier Ah! yep

**Review by jasonkuhrt — APPROVED** [review]

**Pull request merged**
