### PR TITLE
feat: Add CommonFieldConfig to NexusPrismaScalarOpts

### LINKED ISSUE #752: Autogenerated resolver types missing description property
Resolvers for models allow for documenting the field in the graphql schema but currently it doesn't look like it's properly typed.
```js
t.model.stage_name({
  description: "The name an artist as commonly known by",
  alias: "stageName"
});
```

working example

Despite actually working, you get an error saying `description` doesn't exist in `NexusPrismaScalarOpts` including every other non-scalar.

Edit: I seem to be having some other type issues with nexus-prisma-plugin, this issue might be related to that, I'll close if it is

### PR DESCRIPTION
**Pull request by Smona**
Resolves #752 

Adds description and deprecation fields to NexusPrismaScalarOpts by forwarding them directly from the relevant Nexus type. Pulling directly from their interface will prevent type errors should the CommonFieldConfig change in the future.

Both of these fields were already functioning properly, this just fixes the type error when they're supplied.

I tested against my project and confirmed that my type errors were resolved, and property descriptions showed up in VS Code.

### CODE REVIEW

**Comment by jasonkuhrt** [comment]
Rebase, test, docs and then LGTM!

**Comment by Smona** [comment]
@jasonkuhrt sure thing. Just to be clear you're suggesting a pr against https://github.com/graphql-nexus/nexus/tree/main/docs updating the possible options to `t.model`, correct?

**Comment by jasonkuhrt** [comment]
@Smona yep!

**Comment by Smona** [comment]
@jasonkuhrt Alright, smoke tests are in place and documentation PR is referenced above. That PR has some failures but they appear to be unrelated. The tests here should be passing but they failed on a faulty network connection :upside_down_face:

**Comment by jasonkuhrt** [comment]
@Smona cool re-ran and passed now. I will check this out more in depth next week!

**Review by jasonkuhrt — APPROVED** [review]
Ty!!

**Comment by Smona** [comment]
Thanks for maintaining this awesome project!

Can you give a ballpark on when we can expect this to be released?

**Comment by jasonkuhrt** [comment]
@Smona single digit days

**Pull request merged**
