### PR TITLE
feat: support prisma 2 beta 3

### PR DESCRIPTION
**Pull request by jasonkuhrt**
closes graphql-nexus/nexus#766

### CODE REVIEW

**Comment by paniavula** [comment]
Thanks for this. Is this available in 0.8.0-next.3? This version seems to be throwing the below error. Please can you check.
4409 ✕ app unhandledRejection
       | error  Error: Cannot find module '.prisma/client'
       |        Require stack:

**Comment by jasonkuhrt** [comment]
Hey @paniavula, that's right. Can you share a bit more about your setup? How did you get into your state?

**Comment by paniavula** [comment]
Here are the replication steps
1. Created a project using `npx nexus@next`
2. Modified dependency version for "nexus-plugin-prisma" in package.json from "0.7.0" to "0.8.0-next.3"
3. Ran the command `npm run dev` to see the error

**Comment by jasonkuhrt** [comment]
Thanks @paniavula, will investigate that.

**Comment by jasonkuhrt** [comment]
Hey @paniavula there were some hiccups during publishing. I've corrected that in the release for beta 4 support. That should work for you (did for me).

**Comment by paniavula** [comment]
Tested. working. thanks for the quick turnaround.

**Pull request merged**
